### ISSUE TITLE
Animation stops working if the app window is closed

### ISSUE THREAD

**Issue by prayag17** [patzly/doodle-android#41]
Hello, I am facing an issue in which if I close the app window the live wallpaper gets stuck even the the app is running in the background and also not power restrictions are enable and autostar is enabled.

Device: Mi 11x 5G(Global)
OS: Miui 12.5.7
Android Version: 11

**Comment by patzly** [comment]
Hi, please make sure you have reset all options ("Other options" > "Reset all settings"). If the problem stays, please upload a screen recording here which shows me the problem so I can exactly understand it. Thanks!

**Comment by prayag17** [comment]
I did try that but it didn't work

https://imgur.com/a/VLFgzE5

**Comment by patzly** [comment]
That's super weird... I have no idea what's causing this bad behavior😐
I only can say that I think I made nothing wrong with the overall wallpaper service, I only followed the official docs.
That must have to do with MIUI and their battery management... I read that MIUI 12 has an aggressive background service management.
The only solution I can think of is to lock Doodle in recent apps, so it stays always open in background (I read that this is possible in MIUI).
Hope that helps! I will leave this issue open.

**Comment by prayag17** [comment]
I did try locking the app but when the ram is cleared the wallpaper stops and I even turned off the battery optimisation and Miui optimisation too

**Comment by patzly** [comment]
As I said, that's very weird and should not have to do with my code. I don't know why your device stops the wallpaper service if you close the settings app... The wallpaper service runs completely independent from the settings app. 🤷🏼‍♂️

**Comment by patzly** [comment]
What happens if you select the wallpaper in your system's wallpaper picker?
Long-press an empty place on your home screen > Select "Change wallpaper" or something like that > Search for section "Live wallpapers" or "Live" > Select Doodle > Tap on the "SET" button to apply it. Does it work?

(If there is now Live wallpaper section in MIUI you should try to install the Google Wallpaper app from Play Store and use that to select the Doodle wallpaper.)

**Comment by prayag17** [comment]
That suprisingly worked!! Wierd though the zoom out on app drawer doesn't work but that is ok

**Comment by patzly** [comment]
That's perfect, nice to hear! I will include it in the information text.
The missing zoom effect is unrelated to this I think, that's just because they deactivated this in MIUI like Samsung did.

**Comment by prayag17** [comment]
I found another issue after applying the wallpaper and rebooting the phone, the lockscreen text color changes to black even after enabling the force white text option

**Comment by patzly** [comment]
@prayag17 Could you please check the new update? I've implemented a selection when you tap on the big button to set the wallpaper. If you select the left button and then apply it from system wallpaper picker it hopefully works now even when closing the settings app?

**Comment by patzly** [comment]
@prayag17 Yeah that was another bug in the last version but I did not exactly know what caused this... Can you please also look for that and answer here if it works again? The text/icons should be easily readable on dark backgrounds.

**Comment by prayag17** [comment]
Nope both of the issues are still not fixed, the wallpaper has to be applied after force stopping the doodle app and then manually setting it with the google wallpaper app and also the lockscreen text color is still not fix, I think this is might be because MIUI might think the background is white at the boot and then doodle starts and applies the wallpaper leaving the text color black.

**Comment by prayag17** [comment]
I think the text color is set to black is cause it thinks that the background is the preview which is white resulting in white, I found this after applying a theme for MIUI.

**Comment by patzly** [comment]
Yes that has to be the reason, I will look into it as soon as I have time. Why is the background distorted in your image?

**Comment by patzly** [comment]
That's right, the preview thumbnail is static, but I thought that would be your lockscreen and there should not be the preview thumbnail anymore when the wallpaper is applied? :)

**Comment by prayag17** [comment]
Miui is a buggy mess, it is not your code that's the problem but the miui implemention that is the issue

**Comment by prayag17** [comment]
The text issue now fixed in version 5.3.0 but the wallpaper still stops, it works with the work around though

**Comment by patzly** [comment]
@prayag17 That's great! Do you mean the workaround which you can choose when you tap on the big button to set the wallpaper? Is that working for you?

**Comment by prayag17** [comment]
No I mean the work around in which i go to the wallpaper selector and choose doodle not through the apps picker or through the app

**Comment by patzly** [comment]
The left button also opens the system wallpaper picker, does the picker not look the same? So you mean the workaround in the app (dialog with two buttons, left button is the workaround) does not work for you?

**Comment by prayag17** [comment]
Yeah, the background also stops working if I open the app after applying it the the wallpaper picker and close it, so maybe the MIUI background manager is causing the issue

**Comment by patzly** [comment]
Yes this has to be it... But why.. It makes absolutely no sense to kill a live wallpaper service after the parent process has stopped.
So I will remove the workaround in the app and instead write in the info section what you said. Thanks for helping!

**Comment by prayag17** [comment]
You can maybe just flag this issue as Rom-Bug or something

**Comment by patzly** [comment]
I have already opened a ram issue a few days ago. But what do you mean with "doodle uses a wrapper for svgs for the background and this also cause it to use a lot of ram"? Do you know the reason? I don't really know what you mean with wrapper, but if you would know a solution or another more efficient approach, please tell me! I don't know how to make the app use less RAM...

**Comment by prayag17** [comment]
By wrapper I mean that the svg file is being rendered in a canvas which is being used as a wallpaper, maybe convert them to XML vector graphics or some other native Android image format that can directly be used instead of drawing the image on a canvas. You can also maybe reverse engineer a live wallpaper app from Google from the apk( you can find the apk on websites like XDA), I don't code in Java or create Android apps so I don't know that much about Android app ram management system.

A very unlikely and frankly not necessary fix can be to just use a new language like kotlin or maybe use less variables or something, again I don't know how to code an Android app so take what I say with a grain of salt

**Comment by patzly** [comment]
I just stumble upon this issue again, I would say that another language can't fix this issue as it only has to do with the graphics. Also the image format Android Vector Graphic sadly is not efficient at all, it is rendered and cached as big bitmap and therefore is more inefficient than a simple canvas drawing method like Doodle uses it.

**Comment by patzly** [comment]
From #59:
Im currently using MIUI 12, and what I want is the tilt effect. However, I'm running into these issues:

1. I set it my wallpaper from the app.
2. After one minute of inactivity on my device, it turns into a still image.
3. It works when I restart my phone or restart the app, but as mentioned above it works temporarily and turns into a still image after one minute (exactly).

I've tried everything- setting it from the Google Wallpaper app (has no effect), clearing my Themes app data, and making sure the app has full permissions and can bypass battery saver.

I've found a temporary solution. I've seen this issue, but not with a one minute timer, even with the app open.

I used a third party to hide the app, It seems to fix the one minute timer and I do not have to worry about accidentally closing the app (after restarting my phone). Unnefficient, but it works.

I believe this is more on MIUI's side. There may be a timer to stop running apps automatically?

Also, I was reading your response to another post. When I try setting Doodle as a default live wallpaper app in Themes, Doodle just doesn't show up. Same case with Google's wallpaper app.

It shows on Google's Wallpaper app, but doesn't exactly do anything when I click it. It opens a window and immediately closes.

**Comment by bryanoliveira** [comment]
I'm currently using MIUI 13 and using Google's Wallpaper app to set Doodle worked, and it's working even after a reboot. I also enabled "autostart" and disabled Battery Saver restrictions for Doodle. I tried setting it as wallpaper from the Settings and Themes apps but it didn't show up there. Hope this helps someone.

Thanks for the great app!

**Comment by patzly** [comment]
@bryanoliveira thank you! I will write that into the help dialog. What do you mean with "enabled autostart"? Is this an extra option on Xiaomi devices?

**Comment by patzly** [comment]
I updated the help text for the next version, this should make this issue fixed because a working solution (or better a workaround) exists. Thanks again @bryanoliveira for your message!

**Comment by bryanoliveira** [comment]
@patzly yes, it is an extra option. Here's my setup: https://imgur.com/a/QbW3CXi.

However, I think the crucial thing was setting the wallpaper from Google Wallpapers (so the launcher can launch Doodle directly) and disabling Battery Saver, which prevents the system from killing the background process. This Battery Saver option is known to be unreliable on previous MIUI versions though, so either they fixed it or I got lucky.
